name: Sync Branch to Another Repo

on:
  push:
    branches:
      - main

jobs:
  sync_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Add destination repository as a remote
        run: |
          git remote add destination git@github.com:Luis-Corbi/consultorio_front.git
          git fetch destination
          
      - name: Force push changes to destination repository
        run: git push --force -u destination refs/heads/main:refs/heads/main

