name: Sync Branch to Another Repo

on:
  push:
    branches:
      - deploy

jobs:
  sync_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clean and re-clone destination repository
        run: |
          rm -rf temp_repo
          git clone git@github.com:Luis-Corbi/consultorio_front.git temp_repo
          cd temp_repo
          git checkout main || git checkout -b main

      - name: Merge changes and resolve conflicts
        run: |
          cd temp_repo
          git remote add source ${{ github.repository_url }}
          git fetch source
          git merge --no-commit --no-ff source/deploy || true
          
          # Mostrar archivos en conflicto
          git status
          
          # Resolver conflictos tomando los cambios de la rama 'deploy'
          git diff --name-only --diff-filter=U | xargs -I{} git checkout --theirs {}
          git add .
          git commit -m "Merge deploy branch and resolve conflicts" || echo "No changes to commit"

      - name: Verify repository integrity
        run: |
          cd temp_repo
          git fsck --full
          git gc --aggressive --prune=now

      - name: Push changes to destination repository
        run: |
          cd temp_repo
          git push origin main
