name: Sync Branch to Another Repo

on:
  push:
    branches:
      - deploy

jobs:
  sync_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clean and re-clone destination repository
        run: |
          rm -rf temp_repo
          git clone git@github.com:Luis-Corbi/consultorio_front.git temp_repo
          cd temp_repo
          git checkout main || git checkout -b main

      - name: Merge changes from deploy to main
        run: |
          cd temp_repo
          git remote add source ${{ github.workspace }}
          git fetch source
          git merge --allow-unrelated-histories source/deploy

      - name: Verify repository integrity
        run: |
          cd temp_repo
          git fsck --full
          git gc --aggressive --prune=now

      - name: Push changes to destination repository
        run: |
          cd temp_repo
          git push --mirror origin